version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   configuration: python-neo/docs/source/conf.py

python:
   install:
   - requirements: python-neo/docs/requirements_docs.txt 
